import pyxel

WINDOW_WIDTH = 128
WINDOW_HEIGHT = WINDOW_WIDTH

BACKGROUND_COLOR = pyxel.COLOR_BLACK
CELL_COLOR = pyxel.COLOR_DARK_BLUE
UI_HIGHLIGHT_COLOR = pyxel.COLOR_WHITE
UI_SHADOW_COLOR = pyxel.COLOR_GRAY
